language: ruby
before_install:
  - gem install bundler
before_script:
  - rake db:migrate
env:
  global:
    - RAILS_ENV=test  
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
script: bundle exec rake
notifications:
  email:
    - mobile-stat@cwi.com.br
